-- Generated by infra/init/build-company-metrics.mjs — do not edit by hand.
PRAGMA foreign_keys = ON;

INSERT OR REPLACE INTO company_metrics (
  sec_code, edinet_code, filer_name, calc_date, fiscal_month,
  metrics_json, sales, roe, equity_ratio, total_assets, updated_at
) VALUES (
  '1301',
  'E00001',
  'カブトシステムズ株式会社',
  '2025-03-31',
  '03',
  '{"edinetCode":"E00001","secCode":"1301","filerName":"カブトシステムズ株式会社","calcDate":"2025-03-31","fiscalMonth":"03","sales":"720000000000","operatingProfit":"86400000000","recurringProfit":"82800000000","netIncome":"57600000000","comprehensiveIncome":"59040000000","netAssets":"864000000000","totalAssets":"1800000000000","equityRatio":"0.4800","EPS":"133.56","dilutedEPS":"132.22","BPS":"1953.89","ROE":"0.0667","roeCalculated":"0.06666666666666667","roa":"0.032","equityRatioCalculated":"0.48","PER":13.76,"PBR":1.04,"operatingCF":"108000000000","investingCF":"-43200000000","financingCF":"-28800000000","fcf":"64800000000","cashBalance":"144000000000","payoutRatio":"0.2955","payoutRatioComputed":"0.26875","dividendPerShare":"36.00","dividendYield":0.01958879207672538,"sharesOutstanding":"430000000","currentAssets":"648000000000","currentLiabilities":"360000000000","liabilities":"936000000000","investmentSecurities":"32400000000","marketCap":790247808000,"netCash":-183600000000,"netCashRatio":-0.23233218509604522,"salesGrowthYoY":null,"opGrowthYoY":null,"epsGrowthYoY":null,"dividendGrowthYoY":null,"salesCagr3y":null,"salesCagr5y":null,"consecutiveDivIncreases":null,"currentRatio":1.8,"deRatio":1.0833333333333333,"roic":0.06666666666666667,"piotroskiFScore":null}',
  720000000000,
  0.0667,
  0.48,
  1800000000000,
  '2026-06-12T06:47:44.904Z'
);

INSERT OR REPLACE INTO company_metrics (
  sec_code, edinet_code, filer_name, calc_date, fiscal_month,
  metrics_json, sales, roe, equity_ratio, total_assets, updated_at
) VALUES (
  '1302',
  'E00002',
  'ライオンロジスティクス株式会社',
  '2025-03-31',
  '03',
  '{"edinetCode":"E00002","secCode":"1302","filerName":"ライオンロジスティクス株式会社","calcDate":"2025-03-31","fiscalMonth":"03","sales":"780000000000","operatingProfit":"93600000000","recurringProfit":"89700000000","netIncome":"62400000000","comprehensiveIncome":"63960000000","netAssets":"936000000000","totalAssets":"1950000000000","equityRatio":"0.4800","EPS":"144.69","dilutedEPS":"143.24","BPS":"2006.73","ROE":"0.0667","roeCalculated":"0.06666666666666667","roa":"0.032","equityRatioCalculated":"0.48","PER":14.24,"PBR":1.06,"operatingCF":"117000000000","investingCF":"-46800000000","financingCF":"-31200000000","fcf":"70200000000","cashBalance":"156000000000","payoutRatio":"0.3045","payoutRatioComputed":"0.26875","dividendPerShare":"39.00","dividendYield":0.01892849571458857,"sharesOutstanding":"430000000","currentAssets":"702000000000","currentLiabilities":"390000000000","liabilities":"1014000000000","investmentSecurities":"35100000000","marketCap":885965808000,"netCash":-198900000000,"netCashRatio":-0.2245007631265156,"salesGrowthYoY":null,"opGrowthYoY":null,"epsGrowthYoY":null,"dividendGrowthYoY":null,"salesCagr3y":null,"salesCagr5y":null,"consecutiveDivIncreases":null,"currentRatio":1.8,"deRatio":1.0833333333333333,"roic":0.06666666666666667,"piotroskiFScore":null}',
  780000000000,
  0.0667,
  0.48,
  1950000000000,
  '2026-06-12T06:47:44.904Z'
);

INSERT OR REPLACE INTO company_metrics (
  sec_code, edinet_code, filer_name, calc_date, fiscal_month,
  metrics_json, sales, roe, equity_ratio, total_assets, updated_at
) VALUES (
  '1303',
  'E00003',
  'ペンギンソリューションズ株式会社',
  '2025-03-31',
  '03',
  '{"edinetCode":"E00003","secCode":"1303","filerName":"ペンギンソリューションズ株式会社","calcDate":"2025-03-31","fiscalMonth":"03","sales":"850000000000","operatingProfit":"102000000000","recurringProfit":"97750000000","netIncome":"68000000000","comprehensiveIncome":"69700000000","netAssets":"1020000000000","totalAssets":"2125000000000","equityRatio":"0.4800","EPS":"157.67","dilutedEPS":"156.09","BPS":"2065.04","ROE":"0.0667","roeCalculated":"0.06666666666666667","roa":"0.032","equityRatioCalculated":"0.48","PER":14.8,"PBR":1.1,"operatingCF":"127500000000","investingCF":"-51000000000","financingCF":"-34000000000","fcf":"76500000000","cashBalance":"170000000000","payoutRatio":"0.3150","payoutRatioComputed":"0.26875","dividendPerShare":"42.50","dividendYield":0.018212859907538667,"sharesOutstanding":"430000000","currentAssets":"765000000000","currentLiabilities":"425000000000","liabilities":"1105000000000","investmentSecurities":"38250000000","marketCap":1003411880000,"netCash":-216750000000,"netCashRatio":-0.21601298960104,"salesGrowthYoY":null,"opGrowthYoY":null,"epsGrowthYoY":null,"dividendGrowthYoY":null,"salesCagr3y":null,"salesCagr5y":null,"consecutiveDivIncreases":null,"currentRatio":1.8,"deRatio":1.0833333333333333,"roic":0.06666666666666667,"piotroskiFScore":null}',
  850000000000,
  0.0667,
  0.48,
  2125000000000,
  '2026-06-12T06:47:44.904Z'
);

INSERT OR REPLACE INTO company_metrics (
  sec_code, edinet_code, filer_name, calc_date, fiscal_month,
  metrics_json, sales, roe, equity_ratio, total_assets, updated_at
) VALUES (
  '1304',
  'E00004',
  'キツネクラウド株式会社',
  '2025-03-31',
  '03',
  '{"edinetCode":"E00004","secCode":"1304","filerName":"キツネクラウド株式会社","calcDate":"2025-03-31","fiscalMonth":"03","sales":"910000000000","operatingProfit":"109200000000","recurringProfit":"104650000000","netIncome":"72800000000","comprehensiveIncome":"74620000000","netAssets":"1092000000000","totalAssets":"2275000000000","equityRatio":"0.4800","EPS":"168.81","dilutedEPS":"167.12","BPS":"2112.53","ROE":"0.0667","roeCalculated":"0.06666666666666667","roa":"0.032","equityRatioCalculated":"0.48","PER":15.28,"PBR":1.13,"operatingCF":"136500000000","investingCF":"-54600000000","financingCF":"-36400000000","fcf":"81900000000","cashBalance":"182000000000","payoutRatio":"0.3240","payoutRatioComputed":"0.26875","dividendPerShare":"45.50","dividendYield":0.01763964629524007,"sharesOutstanding":"430000000","currentAssets":"819000000000","currentLiabilities":"455000000000","liabilities":"1183000000000","investmentSecurities":"40950000000","marketCap":1109149224000,"netCash":-232050000000,"netCashRatio":-0.2092144095481962,"salesGrowthYoY":null,"opGrowthYoY":null,"epsGrowthYoY":null,"dividendGrowthYoY":null,"salesCagr3y":null,"salesCagr5y":null,"consecutiveDivIncreases":null,"currentRatio":1.8,"deRatio":1.0833333333333333,"roic":0.06666666666666667,"piotroskiFScore":null}',
  910000000000,
  0.0667,
  0.48,
  2275000000000,
  '2026-06-12T06:47:44.904Z'
);

INSERT OR REPLACE INTO company_metrics (
  sec_code, edinet_code, filer_name, calc_date, fiscal_month,
  metrics_json, sales, roe, equity_ratio, total_assets, updated_at
) VALUES (
  '1305',
  'E00005',
  'クジラデータバンク株式会社',
  '2025-03-31',
  '03',
  '{"edinetCode":"E00005","secCode":"1305","filerName":"クジラデータバンク株式会社","calcDate":"2025-03-31","fiscalMonth":"03","sales":"960000000000","operatingProfit":"115200000000","recurringProfit":"110400000000","netIncome":"76800000000","comprehensiveIncome":"78720000000","netAssets":"1152000000000","totalAssets":"2400000000000","equityRatio":"0.4800","EPS":"178.08","dilutedEPS":"176.30","BPS":"2150.54","ROE":"0.0667","roeCalculated":"0.06666666666666667","roa":"0.032","equityRatioCalculated":"0.48","PER":15.68,"PBR":1.16,"operatingCF":"144000000000","investingCF":"-57600000000","financingCF":"-38400000000","fcf":"86400000000","cashBalance":"192000000000","payoutRatio":"0.3315","payoutRatioComputed":"0.26875","dividendPerShare":"48.00","dividendYield":0.0171901644754937,"sharesOutstanding":"430000000","currentAssets":"864000000000","currentLiabilities":"480000000000","liabilities":"1248000000000","investmentSecurities":"43200000000","marketCap":1200686592000,"netCash":-244800000000,"netCashRatio":-0.20388334610469275,"salesGrowthYoY":null,"opGrowthYoY":null,"epsGrowthYoY":null,"dividendGrowthYoY":null,"salesCagr3y":null,"salesCagr5y":null,"consecutiveDivIncreases":null,"currentRatio":1.8,"deRatio":1.0833333333333333,"roic":0.06666666666666667,"piotroskiFScore":null}',
  960000000000,
  0.0667,
  0.48,
  2400000000000,
  '2026-06-12T06:47:44.904Z'
);

INSERT OR REPLACE INTO company_metrics (
  sec_code, edinet_code, filer_name, calc_date, fiscal_month,
  metrics_json, sales, roe, equity_ratio, total_assets, updated_at
) VALUES (
  '1306',
  'E00006',
  'ハリネズミファイナンス株式会社',
  '2025-03-31',
  '03',
  '{"edinetCode":"E00006","secCode":"1306","filerName":"ハリネズミファイナンス株式会社","calcDate":"2025-03-31","fiscalMonth":"03","sales":"1020000000000","operatingProfit":"122400000000","recurringProfit":"117300000000","netIncome":"81600000000","comprehensiveIncome":"83640000000","netAssets":"1224000000000","totalAssets":"2550000000000","equityRatio":"0.4800","EPS":"189.21","dilutedEPS":"187.32","BPS":"2194.44","ROE":"0.0667","roeCalculated":"0.06666666666666667","roa":"0.032","equityRatioCalculated":"0.48","PER":16.16,"PBR":1.19,"operatingCF":"153000000000","investingCF":"-61200000000","financingCF":"-40800000000","fcf":"91800000000","cashBalance":"204000000000","payoutRatio":"0.3405","payoutRatioComputed":"0.26875","dividendPerShare":"51.00","dividendYield":0.016679565530677055,"sharesOutstanding":"430000000","currentAssets":"918000000000","currentLiabilities":"510000000000","liabilities":"1326000000000","investmentSecurities":"45900000000","marketCap":1314782448000,"netCash":-260100000000,"netCashRatio":-0.19782740513128602,"salesGrowthYoY":null,"opGrowthYoY":null,"epsGrowthYoY":null,"dividendGrowthYoY":null,"salesCagr3y":null,"salesCagr5y":null,"consecutiveDivIncreases":null,"currentRatio":1.8,"deRatio":1.0833333333333333,"roic":0.06666666666666667,"piotroskiFScore":null}',
  1020000000000,
  0.0667,
  0.48,
  2550000000000,
  '2026-06-12T06:47:44.904Z'
);

INSERT OR REPLACE INTO company_metrics (
  sec_code, edinet_code, filer_name, calc_date, fiscal_month,
  metrics_json, sales, roe, equity_ratio, total_assets, updated_at
) VALUES (
  '1307',
  'E00007',
  'フクロウメディア株式会社',
  '2025-03-31',
  '03',
  '{"edinetCode":"E00007","secCode":"1307","filerName":"フクロウメディア株式会社","calcDate":"2025-03-31","fiscalMonth":"03","sales":"1080000000000","operatingProfit":"129600000000","recurringProfit":"124200000000","netIncome":"86400000000","comprehensiveIncome":"88560000000","netAssets":"1296000000000","totalAssets":"2700000000000","equityRatio":"0.4800","EPS":"200.34","dilutedEPS":"198.34","BPS":"2236.65","ROE":"0.0667","roeCalculated":"0.06666666666666667","roa":"0.032","equityRatioCalculated":"0.48","PER":16.64,"PBR":1.22,"operatingCF":"162000000000","investingCF":"-64800000000","financingCF":"-43200000000","fcf":"97200000000","cashBalance":"216000000000","payoutRatio":"0.3495","payoutRatioComputed":"0.26875","dividendPerShare":"54.00","dividendYield":0.016198424217292142,"sharesOutstanding":"430000000","currentAssets":"972000000000","currentLiabilities":"540000000000","liabilities":"1404000000000","investmentSecurities":"48600000000","marketCap":1433472768000,"netCash":-275400000000,"netCashRatio":-0.19212084536788354,"salesGrowthYoY":null,"opGrowthYoY":null,"epsGrowthYoY":null,"dividendGrowthYoY":null,"salesCagr3y":null,"salesCagr5y":null,"consecutiveDivIncreases":null,"currentRatio":1.8,"deRatio":1.0833333333333333,"roic":0.06666666666666667,"piotroskiFScore":null}',
  1080000000000,
  0.0667,
  0.48,
  2700000000000,
  '2026-06-12T06:47:44.904Z'
);

INSERT OR REPLACE INTO company_metrics (
  sec_code, edinet_code, filer_name, calc_date, fiscal_month,
  metrics_json, sales, roe, equity_ratio, total_assets, updated_at
) VALUES (
  '1308',
  'E00008',
  'ラッコアセットマネジメント株式会社',
  '2025-03-31',
  '03',
  '{"edinetCode":"E00008","secCode":"1308","filerName":"ラッコアセットマネジメント株式会社","calcDate":"2025-03-31","fiscalMonth":"03","sales":"1140000000000","operatingProfit":"136800000000","recurringProfit":"131100000000","netIncome":"91200000000","comprehensiveIncome":"93480000000","netAssets":"1368000000000","totalAssets":"2850000000000","equityRatio":"0.4800","EPS":"211.47","dilutedEPS":"209.36","BPS":"2277.32","ROE":"0.0667","roeCalculated":"0.06666666666666667","roa":"0.032","equityRatioCalculated":"0.48","PER":17.12,"PBR":1.25,"operatingCF":"171000000000","investingCF":"-68400000000","financingCF":"-45600000000","fcf":"102600000000","cashBalance":"228000000000","payoutRatio":"0.3585","payoutRatioComputed":"0.26875","dividendPerShare":"57.00","dividendYield":0.01574426279063909,"sharesOutstanding":"430000000","currentAssets":"1026000000000","currentLiabilities":"570000000000","liabilities":"1482000000000","investmentSecurities":"51300000000","marketCap":1556757552000,"netCash":-290700000000,"netCashRatio":-0.1867342796099055,"salesGrowthYoY":null,"opGrowthYoY":null,"epsGrowthYoY":null,"dividendGrowthYoY":null,"salesCagr3y":null,"salesCagr5y":null,"consecutiveDivIncreases":null,"currentRatio":1.8,"deRatio":1.0833333333333333,"roic":0.06666666666666667,"piotroskiFScore":null}',
  1140000000000,
  0.0667,
  0.48,
  2850000000000,
  '2026-06-12T06:47:44.904Z'
);

INSERT OR REPLACE INTO company_metrics (
  sec_code, edinet_code, filer_name, calc_date, fiscal_month,
  metrics_json, sales, roe, equity_ratio, total_assets, updated_at
) VALUES (
  '1309',
  'E00009',
  'シロクマエナジー株式会社',
  '2025-03-31',
  '03',
  '{"edinetCode":"E00009","secCode":"1309","filerName":"シロクマエナジー株式会社","calcDate":"2025-03-31","fiscalMonth":"03","sales":"1200000000000","operatingProfit":"144000000000","recurringProfit":"138000000000","netIncome":"96000000000","comprehensiveIncome":"98400000000","netAssets":"1440000000000","totalAssets":"3000000000000","equityRatio":"0.4800","EPS":"222.60","dilutedEPS":"220.37","BPS":"2316.60","ROE":"0.0667","roeCalculated":"0.06666666666666667","roa":"0.032","equityRatioCalculated":"0.48","PER":17.6,"PBR":1.27,"operatingCF":"180000000000","investingCF":"-72000000000","financingCF":"-48000000000","fcf":"108000000000","cashBalance":"240000000000","payoutRatio":"0.3675","payoutRatioComputed":"0.26875","dividendPerShare":"60.00","dividendYield":0.015314873805439843,"sharesOutstanding":"430000000","currentAssets":"1080000000000","currentLiabilities":"600000000000","liabilities":"1560000000000","investmentSecurities":"54000000000","marketCap":1684636800000,"netCash":-306000000000,"netCashRatio":-0.18164152652963536,"salesGrowthYoY":null,"opGrowthYoY":null,"epsGrowthYoY":null,"dividendGrowthYoY":null,"salesCagr3y":null,"salesCagr5y":null,"consecutiveDivIncreases":null,"currentRatio":1.8,"deRatio":1.0833333333333333,"roic":0.06666666666666667,"piotroskiFScore":null}',
  1200000000000,
  0.0667,
  0.48,
  3000000000000,
  '2026-06-12T06:47:44.904Z'
);

INSERT OR REPLACE INTO company_metrics (
  sec_code, edinet_code, filer_name, calc_date, fiscal_month,
  metrics_json, sales, roe, equity_ratio, total_assets, updated_at
) VALUES (
  '1310',
  'E00010',
  'ウサギテクノロジーズ株式会社',
  '2025-03-31',
  '03',
  '{"edinetCode":"E00010","secCode":"1310","filerName":"ウサギテクノロジーズ株式会社","calcDate":"2025-03-31","fiscalMonth":"03","sales":"1260000000000","operatingProfit":"151200000000","recurringProfit":"144900000000","netIncome":"100800000000","comprehensiveIncome":"103320000000","netAssets":"1512000000000","totalAssets":"3150000000000","equityRatio":"0.4800","EPS":"233.73","dilutedEPS":"231.39","BPS":"2354.58","ROE":"0.0667","roeCalculated":"0.06666666666666667","roa":"0.032","equityRatioCalculated":"0.48","PER":18.08,"PBR":1.31,"operatingCF":"189000000000","investingCF":"-75600000000","financingCF":"-50400000000","fcf":"113400000000","cashBalance":"252000000000","payoutRatio":"0.3765","payoutRatioComputed":"0.26875","dividendPerShare":"63.00","dividendYield":0.01490828423538392,"sharesOutstanding":"430000000","currentAssets":"1134000000000","currentLiabilities":"630000000000","liabilities":"1638000000000","investmentSecurities":"56700000000","marketCap":1817110512000,"netCash":-321300000000,"netCashRatio":-0.17681918511734415,"salesGrowthYoY":null,"opGrowthYoY":null,"epsGrowthYoY":null,"dividendGrowthYoY":null,"salesCagr3y":null,"salesCagr5y":null,"consecutiveDivIncreases":null,"currentRatio":1.8,"deRatio":1.0833333333333333,"roic":0.06666666666666667,"piotroskiFScore":null}',
  1260000000000,
  0.0667,
  0.48,
  3150000000000,
  '2026-06-12T06:47:44.904Z'
);

INSERT OR REPLACE INTO company_metrics (
  sec_code, edinet_code, filer_name, calc_date, fiscal_month,
  metrics_json, sales, roe, equity_ratio, total_assets, updated_at
) VALUES (
  '9999',
  'E00000',
  'サンプル株式会社',
  '2025-03-31',
  '03',
  '{"edinetCode":"E00000","secCode":"9999","filerName":"サンプル株式会社","calcDate":"2025-03-31","fiscalMonth":"03","sales":"1000000000000","operatingProfit":"120000000000","recurringProfit":"115000000000","netIncome":"80000000000","comprehensiveIncome":"82000000000","netAssets":"1200000000000","totalAssets":"2500000000000","equityRatio":"0.4800","EPS":"185.50","dilutedEPS":"183.65","BPS":"2180.00","ROE":"0.0667","roeCalculated":"0.06666666666666667","roa":"0.032","equityRatioCalculated":"0.48","PER":16,"PBR":1.18,"operatingCF":"150000000000","investingCF":"-60000000000","financingCF":"-40000000000","fcf":"90000000000","cashBalance":"200000000000","payoutRatio":"0.3375","payoutRatioComputed":"0.26875","dividendPerShare":"50.00","dividendYield":0.016846361185983826,"sharesOutstanding":"430000000","currentAssets":"900000000000","currentLiabilities":"500000000000","liabilities":"1300000000000","investmentSecurities":"45000000000","marketCap":1276240000000,"netCash":-255000000000,"netCashRatio":-0.1998056791825989,"salesGrowthYoY":"-0.10714285714285714","opGrowthYoY":"-0.10714285714285714","epsGrowthYoY":"-0.10714285714285711","dividendGrowthYoY":"-0.10714285714285714","salesCagr3y":"0.013700332595566689","salesCagr5y":"0.02589630491023409","consecutiveDivIncreases":null,"currentRatio":1.8,"deRatio":1.0833333333333333,"roic":0.06666666666666667,"piotroskiFScore":null}',
  1000000000000,
  0.0667,
  0.48,
  2500000000000,
  '2026-06-12T06:47:44.904Z'
);

