META = {
    "CompanyNameCoverPage": "会社名",
    "EDINETCodeDEI": "EDINETコード",
    "FundCodeDEI": "ファンドコード",
    "SecurityCodeDEI": "証券コード",
    "DocumentTitleCoverPage": "提出書類",
    "AccountingStandardsDEI": "会計基準",
    "CurrentFiscalYearStartDateDEI": "当事業年度開始日",
    "CurrentFiscalYearEndDateDEI": "当事業年度終了日",
    "WhetherConsolidatedFinancialStatementsArePreparedDEI": "連結決算の有無",
    "AmendmentFlagDEI": "修正の有無",
    "ReportAmendmentFlagDEI": "記載事項訂正のフラグ",
    "XBRLAmendmentFlagDEI": "XBRL訂正のフラグ",
}

SUMMARY = {
    "NetSalesSummaryOfBusinessResults": "売上高",
    # IFRS 開示の経営指標（NetSales が無い企業向け）
    "RevenueIFRSSummaryOfBusinessResults": "売上収益（IFRS）",
    "OrdinaryIncomeLossSummaryOfBusinessResults": "経常利益",
    "ProfitLossBeforeTaxIFRSSummaryOfBusinessResults": "税引前利益(IFRS)",
    "ComprehensiveIncomeAttributableToOwnersOfParentIFRSSummaryOfBusinessResults": "当期包括利益: 親会社の所有者に帰属（IFRS）",
    "ProfitLossAttributableToOwnersOfParentSummaryOfBusinessResults": "親会社株主に帰属する当期純利益",
    "ProfitLossAttributableToOwnersOfParentIFRSSummaryOfBusinessResults": "親会社株主に帰属する当期純利益 (IFRS)",
    "ComprehensiveIncomeSummaryOfBusinessResults": "包括利益",
    "NetAssetsSummaryOfBusinessResults": "純資産額",
    "TotalAssetsSummaryOfBusinessResults": "総資産額",
    "NetAssetsPerShareSummaryOfBusinessResults": "１株当たり純資産額",
    "BasicEarningsLossPerShareSummaryOfBusinessResults": "１株当たり当期純利益又は当期純損失",
    "DilutedEarningsPerShareSummaryOfBusinessResults": "潜在株式調整後１株当たり当期純利益",
    "EquityToAssetRatioSummaryOfBusinessResults": "自己資本比率",
    "RateOfReturnOnEquitySummaryOfBusinessResults": "自己資本利益率、経営指標等",
    "PriceEarningsRatioSummaryOfBusinessResults": "株価収益率",
    "NetCashProvidedByUsedInOperatingActivitiesSummaryOfBusinessResults": "営業活動によるキャッシュ・フロー",
    "NetCashProvidedByUsedInInvestingActivitiesSummaryOfBusinessResults": "投資活動によるキャッシュ・フロー",
    "NetCashProvidedByUsedInFinancingActivitiesSummaryOfBusinessResults": "財務活動によるキャッシュ・フロー",
    "CashAndCashEquivalentsSummaryOfBusinessResults": "現金及び現金同等物の残高",
    "NumberOfEmployees": "従業員数",
    "AverageNumberOfTemporaryWorkers": "平均臨時雇用人員",
    "PayoutRatioSummaryOfBusinessResults": "配当性向",
    "InterimDividendPaidPerShareSummaryOfBusinessResults": "１株当たり中間配当額",
    "DividendPaidPerShareSummaryOfBusinessResults": "１株当たり配当額",
    "TotalNumberOfIssuedSharesSummaryOfBusinessResults": "発行済株式総数（普通株式）",
    "CapitalStockSummaryOfBusinessResults": "資本金",
    "NetIncomeLossSummaryOfBusinessResults": "当期純利益又は当期純損失",
}


TEXT = {
    "CompanyHistoryTextBlock": "沿革",
    "DescriptionOfBusinessTextBlock": "事業の内容",
    "OverviewOfAffiliatedEntitiesTextBlock": "関係会社の状況",
    "InformationAboutEmployeesTextBlock": "従業員の状況",
    "OverviewOfBusinessResultsTextBlock": "業績等の概要",
    "OverviewOfProductionOrdersReceivedAndSalesTextBlock": "生産、受注及び販売の状況",
    "BusinessPolicyBusinessEnvironmentIssuesToAddressEtcTextBlock": "経営方針、経営環境及び対処すべき課題等",
    "BusinessRisksTextBlock": "事業等のリスク",
    "CriticalContractsForOperationNATextBlock": "経営上の重要な契約等",
    "ResearchAndDevelopmentActivitiesTextBlock": "研究開発活動",
    "AnalysisOfFinancialPositionOperatingResultsAndCashFlowsTextBlock": "財政状態、経営成績及びキャッシュ・フローの状況の分析",
    "OverviewOfCapitalExpendituresEtcTextBlock": "設備投資等の概要",
    "MajorFacilitiesTextBlock": "主要な設備の状況",
    "PlannedAdditionsRetirementsEtcOfFacilitiesTextBlock": "設備の新設、除却等の計画",
    "TotalNumberOfSharesTextBlock": "株式の総数",
    "IssuedSharesTotalNumberOfSharesEtcTextBlock": "発行済株式、株式の総数等",
    "SubscriptionRightsToSharesEtcNATextBlock": "新株予約権等の状況（該当なし）",
    "DescriptionOfRightsPlanNATextBlock": "ライツプランの内容（該当なし）",
    "ChangesInNumberOfIssuedSharesStatedCapitalEtcTextBlock": "発行済株式総数、資本金等の推移",
    "ShareholdingByShareholderCategoryTextBlock": "所有者別状況",
    "MajorShareholdersTextBlock": "大株主の状況",
    "IssuedSharesVotingRightsTextBlock": "発行済株式、議決権の状況",
    "TreasurySharesEtcTextBlock": "自己株式等",
    "ClassesOfSharesEtcTextBlock": "株式の種類等",
    "AcquisitionsByResolutionOfShareholdersMeetingNATextBlock": "株主総会決議による取得の状況（該当なし）",
    "AcquisitionsByResolutionOfBoardOfDirectorsMeetingNATextBlock": "取締役会決議による取得の状況（該当なし）",
    "AcquisitionsNotBasedOnResolutionOfShareholdersMeetingOrBoardOfDirectorsMeetingTextBlock": "株主総会決議又は取締役会決議に基づかないものの内容",
    "DisposalsOrHoldingOfAcquiredTreasurySharesTextBlock": "取得自己株式の処理状況及び保有状況",
    "DividendPolicyTextBlock": "配当政策",
    "HighestAndLowestSharePriceOfEachFiscalYearInLastFiveYearsTextBlock": "最近5年間の事業年度別最高・最低株価",
    "HighestAndLowestSharePriceOfEachMonthInLastSixMonthsTextBlock": "最近6月間の月別最高・最低株価",
    "InformationAboutOfficersTextBlock": "役員の状況",
    "ExplanationAboutCorporateGovernanceTextBlock": "コーポレート・ガバナンスの状況 [テキストブロック",
    "DetailsOfRemunerationToIndependentAuditorsTextBlock": "監査公認会計士等に対する報酬の内容",
    "OtherMaterialRemunerationToIndependentAuditorsNATextBlock": "その他重要な報酬の内容（該当なし）",
    "DetailsOfNonAuditServicesRenderedByIndependentAuditorsNATextBlock": "監査公認会計士等の提出会社に対する非監査業務の内容（該当なし）",
    "PolicyOnDeterminingAuditFeeTextBlock": "監査報酬の決定方針",
    "RegulationsInAccordanceWithWhichConsolidatedFinancialStatementsHaveBeenPreparedFinancialInformation": "連結財務諸表が基づく規則、経理の状況",
    "RegulationsInAccordanceWithWhichFinancialStatementsHaveBeenPreparedFinancialInformation": "財務諸表が基づく規則、経理の状況",
    "DescriptionOfFactThatFinancialStatementsHaveBeenPreparedInAccordanceWithSpecialProvisionFinancialInformation": "特例財務諸表を作成する場合の記載、経理の状況",
    "NoteOnIndependentAuditFinancialInformation": "監査証明について、経理の状況",
    "RemarkableEffortsToEnsureFairPresentationOfConsolidatedFinancialStatementsEtcFinancialInformation": "連結財務諸表等の適正性を確保するための特段の取組み、経理の状況",
    "ConsolidatedBalanceSheetTextBlock": "連結貸借対照表",
    "ConsolidatedStatementOfIncomeTextBlock": "連結損益計算書",
    "ConsolidatedStatementOfComprehensiveIncomeTextBlock": "連結包括利益計算書",
    "ConsolidatedStatementOfChangesInEquityTextBlock": "連結株主資本等変動計算書",
    "ConsolidatedStatementOfCashFlowsTextBlock": "連結キャッシュ・フロー計算書",
    "NotesSignificantAccountingPoliciesForPreparationOfConsolidatedFinancialStatementsTextBlock": "連結財務諸表作成のための基本となる重要な事項",
    "NumberOfConsolidatedSubsidiariesAndNamesOfMajorConsolidatedSubsidiariesTextBlock": "連結子会社の数及び主要な連結子会社の名称",
    "NamesOfMajorUnconsolidatedSubsidiariesAndReasonsForExclusionFromScopeOfConsolidationTextBlock": "主要な非連結子会社の名称及び連結の範囲から除いた理由",
}


BS = {
    "資産": {
        "流動資産": {
            "CashAndDeposits": "現金及び預金",
            "CashAndCashEquivalents": "現金及び現金同等物",
            "NotesAndAccountsReceivableTrade": "受取手形及び売掛金",
            "ElectronicallyRecordedMonetaryClaimsOperatingCA": "電子記録債権",
            "AccountsReceivableTrade": "売掛金",
            "AccountsReceivableOther": "未収入金",
            "ShortTermInvestmentSecurities": "有価証券",
            "Inventories": "棚卸資産",
            "MerchandiseAndFinishedGoods": "商品及び製品",
            "Merchandise": "商品",
            "PrepaidExpenses": "前払費用",
            "WorkInProcess": "仕掛品",
            "RawMaterials": "原材料",
            "RawMaterialsAndSupplies": "原材料及び貯蔵品",
            "DeferredTaxAssetsCA": "繰延税金資産",
            "OtherCA": "その他",
            "ShortTermLoansReceivableToSubsidiariesAndAffiliates": "関係会社短期貸付金",
            "AllowanceForDoubtfulAccountsCA": "貸倒引当金",
            "CurrentAssets": "流動資産",
        },
        "非流動資産": {
            "有形固定資産": {
                "Buildings": "建物",
                "Structures": "構築物",
                "建物及び構築物": {
                    "BuildingsAndStructures": "建物及び構築物",
                    "AccumulatedDepreciationBuildingsAndStructures": "減価償却累計額、建物及び構築物",
                    "BuildingsAndStructuresNet": "建物及び構築物（純額）",
                },
                "MachineryAndEquipment": "機械及び装置",
                "Vehicles": "車両運搬具",
                "機械装置及び運搬具": {
                    "MachineryEquipmentAndVehicles": "機械装置及び運搬具",
                    "AccumulatedDepreciationMachineryEquipmentAndVehicles": "減価償却累計額、機械装置及び運搬具",
                    "MachineryEquipmentAndVehiclesNet": "機械装置及び運搬具（純額）",
                },
                "ToolsFurnitureAndFixtures": "工具、器具及び備品",
                "Land": "土地",
                "LeaseAssetsPPE": "リース資産",
                "ConstructionInProgress": "建設仮勘定",
                "AccumulatedDepreciationPPEByGroup": "減価償却累計額",
                "その他": {
                    "OtherPPE": "その他、有形固定資産",
                    "AccumulatedDepreciationOtherPPE": "減価償却累計額、その他、有形固定資産",
                    "OtherNetPPE": "その他（純額）、有形固定資産",
                },
                "PropertyPlantAndEquipment": "有形固定資産",
            },
            "無形固定資産": {
                "IntangibleAssets": "無形固定資産",
            },
            "投資その他の資産": {
                "InvestmentSecurities": "投資有価証券",
                "StocksOfSubsidiariesAndAffiliates": "関係会社株式",
                "InvestmentsInCapitalOfSubsidiariesAndAffiliates": "関係会社出資金",
                "DeferredTaxAssetsIOA": "繰延税金資産、投資その他の資産",
                "NetDefinedBenefitAsset": "退職給付に係る資産",
                "OtherIOA": "その他、投資その他の資産",
                "AllowanceForDoubtfulAccountsIOAByGroup": "貸倒引当金、投資その他の資産、一括控除",
                "InvestmentsAndOtherAssets": "投資その他の資産",
            },
            "NoncurrentAssets": "固定資産",
        },
        "繰延資産": {
            "BondIssuanceCostDA": "社債発行費、繰延資産",
            "DeferredAssets": "繰延資産",
        },
        "Assets": "総資産",
    },
    "負債": {
        "流動負債": {
            "NotesPayableTrade": "支払手形",
            "NotesAndAccountsPayableTrade": "支払手形及び買掛金",
            "AccountsPayableTrade": "買掛金",
            "ShortTermLoansPayable": "短期借入金",
            "CurrentPortionOfLongTermLoansPayable": "１年内返済予定の長期借入金",
            "CurrentPortionOfBonds": "１年内償還予定の社債",
            "AccruedExpenses": "未払費用",
            "DeferredTaxLiabilitiesCL": "繰延税金負債",
            "IncomeTaxesPayable": "未払法人税等",
            "DepositsReceived": "預り金",
            "ProvisionForBonuses": "賞与引当金",
            "OtherCL": "その他",
            "InterestBearingLiabilitiesCL": "有利子負債",
            "TotalCurrentLiabilities": "流動負債",
            "CurrentLiabilities": "流動負債",
        },
        "非流動負債": {
            "BondsPayable": "社債",
            "LongTermLoansPayable": "長期借入金",
            "DeferredTaxLiabilitiesNCL": "繰延税金負債",
            "ProvisionForRetirementBenefits": "退職給付引当金",
            "ProvisionForDirectorsRetirementBenefits": "役員退職慰労引当金",
            "ProvisionForEnvironmentalMeasuresNCL": "環境対策引当金",
            "NetDefinedBenefitLiability": "退職給付に係る負債",
            "OtherNCL": "その他",
            "NoncurrentLiabilities": "非流動負債",
        },
        "Liabilities": "負債",
    },
    "純資産": {
        "株主資本": {
            "CapitalStock": "資本金",
            "資本剰余金": {
                "LegalCapitalSurplus": "資本準備金",
                "OtherCapitalSurplus": "その他資本剰余金",
                "CapitalSurplus": "資本剰余金",
            },
            "利益剰余金": {
                "その他利益剰余金": {
                    "ReserveForAdvancedDepreciationOfNoncurrentAssets": "固定資産圧縮積立金",
                    "GeneralReserve": "別途積立金",
                    "RetainedEarningsBroughtForward": "繰越利益剰余金",
                },
                "RetainedEarnings": "利益剰余金",
            },
            "TreasuryStock": "自己株式",
            "ShareholdersEquity": "株主資本",
        },
        "その他の包括利益累計額": {
            "ValuationDifferenceOnAvailableForSaleSecurities": "その他有価証券評価差額金",
            "DeferredGainsOrLossesOnHedges": "繰延ヘッジ損益",
            "ForeignCurrencyTranslationAdjustment": "為替換算調整勘定",
            "ValuationAndTranslationAdjustments": "評価・換算差額等",
        },
        "NonControllingInterests": "非支配株主持分",
        "NetAssetsSummaryOfBusinessResults": "純資産",
        "NetAssets": "純資産",
    },
    "負債及び純資産": {
        "LiabilitiesAndEquity": "負債及び純資産",
        "LiabilitiesAndNetAssets": "負債及び純資産",
    },
}

# 包括利益計算書
COMPREHENSIVE_INCOME = {
    "ProfitLoss": "当期純利益",
    "その他の包括利益": {
        "ValuationDifferenceOnAvailableForSaleSecuritiesNetOfTaxOCI": "その他有価証券評価差額金（税引後）",
        "DeferredGainsOrLossesOnHedgesNetOfTaxOCI": "繰延ヘッジ損益（税引後）",
        "ForeignCurrencyTranslationAdjustmentNetOfTaxOCI": "為替換算調整勘定（税引後）",
        "OtherComprehensiveIncome": "その他の包括利益",
        "ComprehensiveIncome": "包括利益",
        "ComprehensiveIncomeAttributableToOwnersOfTheParent": "親会社株主に係る包括利益",
        "ComprehensiveIncomeAttributableToNonControllingInterests": "非支配株主に係る包括利益",
    },
}


PL = {
    "売上高": {
        "NetSales": "売上高",
        # 連結損益計算書（IFRS）の売上収益
        "RevenueIFRS": "売上収益（IFRS）",
    },
    "売上原価": {
        "CostOfSales": "売上原価",
    },
    "売上総利益": {
        "GrossProfit": "売上総利益又は売上総損失（△)",
    },
    "金融事業に係る金融費用": {
        "CostOfFinancingOperations": "金融事業に係る金融費用",
    },
    "販売費及び一般管理費合計": {
        "SellingExpensesSGA": "販売費",
        "GeneralAndAdministrativeExpensesSGA": "一般管理費",
        "SellingGeneralAndAdministrativeExpenses": "販売費及び一般管理費",
    },
    "営業利益": {
        "OperatingExpenses": "売上原価並びに販売費及び一般管理費合計",
        "TotalNetRevenues": "営業収益合計",
        "OperatingProfitLoss": "営業利益",
        "OperatingIncome": "営業利益",
    },
    "営業外収益": {
        "InterestIncomeNOI": "受取利息",
        "DividendsIncomeNOI": "受取配当金",
        "ForeignExchangeGainsNOI": "為替差益",
        "OtherNOI": "その他",
        "NonOperatingIncome": "営業外収益",
    },
    "営業外費用": {
        "InterestExpensesNOE": "支払利息",
        "OtherNOE": "その他",
        "NonOperatingExpenses": "営業外費用",
    },
    "経常利益": {
        "OrdinaryIncome": "経常利益",
    },
    "特別利益": {
        "GainOnSalesOfNoncurrentAssetsEI": "固定資産売却益",
        "GainOnSalesOfInvestmentSecuritiesEI": "投資有価証券売却益",
        "CompensationForTransferEI": "移転補償金",
        "GainOnNegativeGoodwillEI": "負ののれん発生益",
        "ExtraordinaryIncome": "特別利益合計",
    },
    "特別損失": {
        "ImpairmentLossEL": "減損損失",
        "LegalFeeEL": "弁護士報酬等",
        "ProvisionForEnvironmentalMeasuresEL": "環境対策引当金繰入額",
        "ProvisionOfAllowanceForDoubtfulAccountsForSubsidiariesAndAffiliatesEL": "関係会社貸倒引当金繰入額",
        "LossOnValuationOfInvestmentSecuritiesEL": "投資有価証券評価損",
        "LossOnValuationOfStocksOfSubsidiariesAndAffiliatesEL": "関係会社株式評価",
        "OtherEL": "その他",
        "ExtraordinaryLoss": "特別損失合計",
    },
    "税引前利益": {
        "ProfitLossBeforeTax": "税引前利益",
        "IncomeBeforeIncomeTaxes": "税引前利益",
    },
    "IncomeTaxesCurrent": "法人税、住民税及び事業税",
    "IncomeTaxesDeferred": "法人税等調整額",
    "法人税等合計": {
        "IncomeTaxes": "法人所得税費用",
    },
    "当期純利益": {
        "ProfitLoss": "当期利益",
    },
    "ProfitLossAttributableToNonControllingInterests": "非支配株主に帰属する当期純利益",
    "ProfitLossAttributableToOwnersOfParent": "親会社株主に帰属する当期純利益",
}


# CF
CF = {
    "当期利益": {
        "ProfitLoss": "当期利益",
    },
    "営業キャッシュフロー": {
        "IncomeBeforeIncomeTaxes": "税引前当期純利益",
        "減価償却費及び償却費": {
            "DepreciationAndAmortizationOpeCF": "減価償却費及び償却費",
        },
        "ImpairmentLossOpeCF": "減損損失",
        "LossGainOnSalesOfNoncurrentAssetsOpeCF": "固定資産売却損益（△は益）",
        "LossGainOnSalesAndValuationOfInvestmentSecuritiesOpeCF": "投資有価証券売却及び評価損益（△は益）",
        "GainOnNegativeGoodwillOpeCF": "負ののれん発生益",
        "IncreaseDecreaseInAllowanceForDoubtfulAccountsOpeCF": "貸倒引当金の増減額（△は減少）",
        "IncreaseDecreaseInProvisionForBonusesOpeCF": "賞与引当金の増減額（△は減少）",
        "IncreaseDecreaseInProvisionForEnvironmentalMeasuresOpeCF": "環境対策引当金の増減額（△は減少）",
        "IncreaseDecreaseInNetDefinedBenefitAssetAndLiabilityOpeCF": "退職給付に係る資産及び負債の増減額",
        "InterestAndDividendsIncomeOpeCF": "受取利息及び受取配当金",
        "InterestExpensesOpeCF": "支払利息",
        "DecreaseIncreaseInNotesAndAccountsReceivableTradeOpeCF": "売上債権の増減額（△は増加）",
        "DecreaseIncreaseInInventoriesOpeCF": "棚卸資産の増減額（△は増加）",
        "IncreaseDecreaseInNotesAndAccountsPayableTradeOpeCF": "仕入債務の増減額（△は減少）",
        "IncreaseDecreaseInAdvancesReceivedOpeCF": "前受金の増減額（△は減少）",
        "OtherNetOpeCF": "その他",
        "InterestAndDividendsIncomeReceivedOpeCFInvCF": "利息及び配当金の受取額",
        "InterestExpensesPaidOpeCFFinCF": "利息の支払額",
        "IncomeTaxesPaidOpeCF": "法人税等の支払額",
        "NetCashProvidedByUsedInOperatingActivities": "営業キャッシュフロー",
    },
    "投資キャッシュフロー": {
        "ProceedsFromSalesOfPropertyPlantAndEquipmentInvCF": "有形固定資産の売却による収入",
        "PurchaseOfInvestmentSecuritiesInvCF": "投資有価証券の取得による支出",
        "ProceedsFromSalesOfInvestmentSecuritiesInvCF": "投資有価証券の売却による収入",
        "ProceedsFromPurchaseOfInvestmentsInSubsidiariesResultingInChangeInScopeOfConsolidationInvCF": "連結の範囲の変更を伴う子会社株式の取得による収入",
        "OtherNetInvCF": "その他",
        "NetCashProvidedByUsedInInvestingActivities": "投資キャッシュフロー",
        "NetCashProvidedByUsedInInvestingActivitiesSummaryOfBusinessResults": "投資キャッシュフロー",
    },
    "財務キャッシュフロー": {
        "NetIncreaseDecreaseInShortTermLoansPayableFinCF": "短期借入金の純増減額（△は減少）",
        "ProceedsFromLongTermLoansPayableFinCF": "長期借入れによる収入",
        "RepaymentOfLongTermLoansPayableFinCF": "長期借入金の返済による支出",
        "ProceedsFromIssuanceOfBondsFinCF": "社債の発行による収入",
        "RedemptionOfBondsFinCF": "社債の償還による支出",
        "PurchaseOfTreasuryStockFinCF": "自己株式の取得による支出",
        "RepaymentsOfFinanceLeaseObligationsFinCF": "ファイナンス・リース債務の返済による支出",
        "CashDividendsPaidFinCF": "配当金の支払額",
        # IFRS 連結キャッシュ・フロー計算書の配当支払（日本基準の CashDividendsPaidFinCF が無い場合）
        "DividendsPaidFinCFIFRS": "配当金の支払額（IFRS）",
        "OtherNetFinCF": "その他",
        "NetCashProvidedByUsedInFinancingActivities": "財務キャッシュフロー",
    },
    "EffectOfExchangeRateChangeOnCashAndCashEquivalents": "現金及び現金同等物に係る換算差額",
    "現金及び現金同等物の増減額": {
        "NetIncreaseDecreaseInCashAndCashEquivalents": "現金及び現金同等物の増減額",
    },
    "現金及び現金同等物": {
        "CashAndCashEquivalents": "現金及び現金同等物",
    },
}
