-- Generated by infra/init/build-company-metrics.mjs — do not edit by hand.
PRAGMA foreign_keys = ON;

INSERT OR REPLACE INTO company_metrics (
  sec_code, edinet_code, filer_name, calc_date, fiscal_month,
  metrics_json, sales, roe, equity_ratio, total_assets, updated_at
) VALUES (
  '1301',
  'E00001',
  'カブトシステムズ株式会社',
  '2025-03-31',
  '03',
  '{"edinetCode":"E00001","secCode":"1301","filerName":"カブトシステムズ株式会社","calcDate":"2025-03-31","fiscalMonth":"03","sales":"1483436773880","operatingProfit":"107240913111","recurringProfit":"105403143497","netIncome":"58371983809","comprehensiveIncome":"59831283404","netAssets":"284058192726","totalAssets":"528318565082","equityRatio":"0.5377","EPS":"86.99","dilutedEPS":"85.69","BPS":"423.34","ROE":"0.2055","roeCalculated":"0.20549304791678757","roa":"0.11048633848394125","equityRatioCalculated":"0.5376646052214945","PER":8.39,"PBR":3.62,"operatingCF":"135684577469","investingCF":"-136815648217","financingCF":"-74275510493","fcf":"-1131070748","cashBalance":"191959136342","payoutRatio":"0.6039","payoutRatioComputed":"0.6038449903524676","dividendPerShare":"52.53","dividendYield":0.07197407782270811,"sharesOutstanding":"671000000","currentAssets":"252525875530","currentLiabilities":"108826372657","liabilities":"244260372356","investmentSecurities":"95106539001","marketCap":489726733100,"netCash":106468006017,"netCashRatio":0.21740288781674436,"salesGrowthYoY":"0.2238353944562777","opGrowthYoY":"0.223835394446903","epsGrowthYoY":"0.22383230163196394","dividendGrowthYoY":"0.22361984626135573","salesCagr3y":null,"salesCagr5y":null,"consecutiveDivIncreases":2,"currentRatio":2.320447418806409,"deRatio":0.8598955376429201,"roic":0.20549304791678757,"piotroskiFScore":8}',
  1483436773880,
  0.2055,
  0.5377,
  528318565082,
  '2026-06-13T10:45:49.399Z'
);

INSERT OR REPLACE INTO company_metrics (
  sec_code, edinet_code, filer_name, calc_date, fiscal_month,
  metrics_json, sales, roe, equity_ratio, total_assets, updated_at
) VALUES (
  '1302',
  'E00002',
  'ライオンロジスティクス株式会社',
  '2025-03-31',
  '03',
  '{"edinetCode":"E00002","secCode":"1302","filerName":"ライオンロジスティクス株式会社","calcDate":"2025-03-31","fiscalMonth":"03","sales":"1470621230092","operatingProfit":"351439116571","recurringProfit":"333888378816","netIncome":"241599566662","comprehensiveIncome":"247639555829","netAssets":"1491361591817","totalAssets":"2274332414134","equityRatio":"0.6557","EPS":"936.43","dilutedEPS":"922.38","BPS":"5780.47","ROE":"0.1620","roeCalculated":"0.16199932195360298","roa":"0.1062287839546068","equityRatioCalculated":"0.6557359788520041","PER":41.11,"PBR":0.43,"operatingCF":"150022026781","investingCF":"-116462580587","financingCF":"-52078709933","fcf":"33559446194","cashBalance":"230332081731","payoutRatio":"0.1927","payoutRatioComputed":"0.19273147151436426","dividendPerShare":"180.48","dividendYield":0.004688201688722563,"sharesOutstanding":"258000000","currentAssets":"584553190419","currentLiabilities":"254739447899","liabilities":"782970822317","investmentSecurities":"21099980649","marketCap":9932132423400,"netCash":-43707706080,"netCashRatio":-0.004400636662578632,"salesGrowthYoY":"0.1626849930914216","opGrowthYoY":"0.162684993092008","epsGrowthYoY":"0.16267491091493771","dividendGrowthYoY":"0.16266185659988405","salesCagr3y":null,"salesCagr5y":null,"consecutiveDivIncreases":2,"currentRatio":2.294710125346451,"deRatio":0.5250040141928743,"roic":0.16199932195360298,"piotroskiFScore":6}',
  1470621230092,
  0.162,
  0.6557,
  2274332414134,
  '2026-06-13T10:45:49.399Z'
);

INSERT OR REPLACE INTO company_metrics (
  sec_code, edinet_code, filer_name, calc_date, fiscal_month,
  metrics_json, sales, roe, equity_ratio, total_assets, updated_at
) VALUES (
  '1303',
  'E00003',
  'ペンギンソリューションズ株式会社',
  '2025-03-31',
  '03',
  '{"edinetCode":"E00003","secCode":"1303","filerName":"ペンギンソリューションズ株式会社","calcDate":"2025-03-31","fiscalMonth":"03","sales":"148395803693","operatingProfit":"19277727977","recurringProfit":"17754392524","netIncome":"12106170283","comprehensiveIncome":"12408824540","netAssets":"55966322188","totalAssets":"90450093223","equityRatio":"0.6188","EPS":"33.17","dilutedEPS":"32.67","BPS":"153.33","ROE":"0.2163","roeCalculated":"0.21631169978140427","roa":"0.13384364627632683","equityRatioCalculated":"0.6187536153226282","PER":40.88,"PBR":1.3,"operatingCF":"17030169425","investingCF":"-6768185664","financingCF":"-2248513181","fcf":"10261983761","cashBalance":"29647179851","payoutRatio":"0.1385","payoutRatioComputed":"0.13838810795124845","dividendPerShare":"4.59","dividendYield":0.0033849817137240577,"sharesOutstanding":"365000000","currentAssets":"13594358421","currentLiabilities":"17792216252","liabilities":"34483771035","investmentSecurities":"5214280540","marketCap":494936204000,"netCash":17577859989,"netCashRatio":0.035515405514768124,"salesGrowthYoY":"-0.0759710090989949","opGrowthYoY":"-0.07597100907334259","epsGrowthYoY":"-0.07578712733351906","dividendGrowthYoY":"-0.07645875251509053","salesCagr3y":null,"salesCagr5y":null,"consecutiveDivIncreases":0,"currentRatio":0.7640621173021026,"deRatio":0.6161521730722879,"roic":0.21631169978140427,"piotroskiFScore":7}',
  148395803693,
  0.2163,
  0.6188,
  90450093223,
  '2026-06-13T10:45:49.399Z'
);

INSERT OR REPLACE INTO company_metrics (
  sec_code, edinet_code, filer_name, calc_date, fiscal_month,
  metrics_json, sales, roe, equity_ratio, total_assets, updated_at
) VALUES (
  '1304',
  'E00004',
  'キツネクラウド株式会社',
  '2025-03-31',
  '03',
  '{"edinetCode":"E00004","secCode":"1304","filerName":"キツネクラウド株式会社","calcDate":"2025-03-31","fiscalMonth":"03","sales":"1179513517983","operatingProfit":"240250235998","recurringProfit":"230317330565","netIncome":"155538896554","comprehensiveIncome":"159427368968","netAssets":"833544781895","totalAssets":"1246768838024","equityRatio":"0.6686","EPS":"270.97","dilutedEPS":"266.91","BPS":"1452.17","ROE":"0.1866","roeCalculated":"0.18659932847326363","roa":"0.12475359650511726","equityRatioCalculated":"0.6685640164186991","PER":19.98,"PBR":2.35,"operatingCF":"208523878646","investingCF":"-90690476451","financingCF":"-42258358567","fcf":"117833402195","cashBalance":"135209361107","payoutRatio":"0.1475","payoutRatioComputed":"0.14746819289692414","dividendPerShare":"39.96","dividendYield":0.007380890873528434,"sharesOutstanding":"574000000","currentAssets":"352258401374","currentLiabilities":"173951536552","liabilities":"413224056129","investmentSecurities":"20230022787","marketCap":3107624864400,"netCash":-9419058538,"netCashRatio":-0.003030950950966397,"salesGrowthYoY":"0.2747249162014232","opGrowthYoY":"0.2747249162006405","epsGrowthYoY":"0.2747330291198195","dividendGrowthYoY":"0.2746411483253588","salesCagr3y":null,"salesCagr5y":null,"consecutiveDivIncreases":2,"currentRatio":2.0250375958518654,"deRatio":0.495743078361749,"roic":0.18659932847326363,"piotroskiFScore":8}',
  1179513517983,
  0.1866,
  0.6686,
  1246768838024,
  '2026-06-13T10:45:49.399Z'
);

INSERT OR REPLACE INTO company_metrics (
  sec_code, edinet_code, filer_name, calc_date, fiscal_month,
  metrics_json, sales, roe, equity_ratio, total_assets, updated_at
) VALUES (
  '1305',
  'E00005',
  'クジラデータバンク株式会社',
  '2025-03-31',
  '03',
  '{"edinetCode":"E00005","secCode":"1305","filerName":"クジラデータバンク株式会社","calcDate":"2025-03-31","fiscalMonth":"03","sales":"1276346942823","operatingProfit":"208342457520","recurringProfit":"194999552537","netIncome":"186546030192","comprehensiveIncome":"191209680946","netAssets":"925127256564","totalAssets":"1731786279619","equityRatio":"0.5342","EPS":"405.53","dilutedEPS":"399.45","BPS":"2011.15","ROE":"0.2016","roeCalculated":"0.20164364293497045","roa":"0.10771885213979226","equityRatioCalculated":"0.5342040570777197","PER":41.24,"PBR":1.94,"operatingCF":"175584790789","investingCF":"-121836848932","financingCF":"60588263377","fcf":"53747941857","cashBalance":"167414085188","payoutRatio":"0.0838","payoutRatioComputed":"0.083765920850296","dividendPerShare":"33.97","dividendYield":0.0020312056813582293,"sharesOutstanding":"460000000","currentAssets":"573667444344","currentLiabilities":"319665354587","liabilities":"806659023055","investmentSecurities":"45231863513","marketCap":7693066312000,"netCash":-114916572881,"netCashRatio":-0.014937681312033905,"salesGrowthYoY":"0.06469325294679555","opGrowthYoY":"0.06469325294426848","epsGrowthYoY":"0.06469059308461757","dividendGrowthYoY":"0.06455656534001876","salesCagr3y":null,"salesCagr5y":null,"consecutiveDivIncreases":2,"currentRatio":1.7945874837927451,"deRatio":0.8719438513259236,"roic":0.20164364293497045,"piotroskiFScore":5}',
  1276346942823,
  0.2016,
  0.5342,
  1731786279619,
  '2026-06-13T10:45:49.399Z'
);

INSERT OR REPLACE INTO company_metrics (
  sec_code, edinet_code, filer_name, calc_date, fiscal_month,
  metrics_json, sales, roe, equity_ratio, total_assets, updated_at
) VALUES (
  '1306',
  'E00006',
  'ハリネズミファイナンス株式会社',
  '2025-03-31',
  '03',
  '{"edinetCode":"E00006","secCode":"1306","filerName":"ハリネズミファイナンス株式会社","calcDate":"2025-03-31","fiscalMonth":"03","sales":"2699055735097","operatingProfit":"339132173410","recurringProfit":"332532000860","netIncome":"311866969135","comprehensiveIncome":"319663643363","netAssets":"4214580996077","totalAssets":"11894272956019","equityRatio":"0.3543","EPS":"1134.06","dilutedEPS":"1117.05","BPS":"15325.75","ROE":"0.0740","roeCalculated":"0.07399714691099561","roa":"0.026219927042886827","equityRatioCalculated":"0.3543369999714229","PER":25.14,"PBR":2.08,"operatingCF":"368411689715","investingCF":"-171253425991","financingCF":"231402372343","fcf":"197158263724","cashBalance":"241800162189","payoutRatio":"0.0830","payoutRatioComputed":"0.08298490241458382","dividendPerShare":"94.11","dividendYield":0.0033009159605105645,"sharesOutstanding":"275000000","currentAssets":"7608920263626","currentLiabilities":"4403899953160","liabilities":"7679691959942","investmentSecurities":"130195881624","marketCap":7840323810000,"netCash":-2446092023791,"netCashRatio":-0.31198864779935664,"salesGrowthYoY":"0.16361651161648888","opGrowthYoY":"0.1636165116152817","epsGrowthYoY":"0.16361584239688068","dividendGrowthYoY":"0.1635756676557864","salesCagr3y":null,"salesCagr5y":null,"consecutiveDivIncreases":2,"currentRatio":1.7277686470071263,"deRatio":1.82217211321609,"roic":0.07399714691099561,"piotroskiFScore":7}',
  2699055735097,
  0.074,
  0.3543,
  11894272956019,
  '2026-06-13T10:45:49.399Z'
);

INSERT OR REPLACE INTO company_metrics (
  sec_code, edinet_code, filer_name, calc_date, fiscal_month,
  metrics_json, sales, roe, equity_ratio, total_assets, updated_at
) VALUES (
  '1307',
  'E00007',
  'フクロウメディア株式会社',
  '2025-03-31',
  '03',
  '{"edinetCode":"E00007","secCode":"1307","filerName":"フクロウメディア株式会社","calcDate":"2025-03-31","fiscalMonth":"03","sales":"2767719068233","operatingProfit":"650715012941","recurringProfit":"608753994560","netIncome":"366945707875","comprehensiveIncome":"376119350572","netAssets":"7914145931457","totalAssets":"20980301787497","equityRatio":"0.3772","EPS":"606.52","dilutedEPS":"597.42","BPS":"13081.23","ROE":"0.0464","roeCalculated":"0.046365800056386505","roa":"0.017490010944155133","equityRatioCalculated":"0.3772179262060642","PER":35.24,"PBR":2.26,"operatingCF":"439603434833","investingCF":"-371067800483","financingCF":"89573543440","fcf":"68535634350","cashBalance":"344878090815","payoutRatio":"0.4257","payoutRatioComputed":"0.42567305366386554","dividendPerShare":"258.18","dividendYield":0.012079294519045143,"sharesOutstanding":"605000000","currentAssets":"7642509487601","currentLiabilities":"7018024789327","liabilities":"13066155856040","investmentSecurities":"97569550719","marketCap":12931127704000,"netCash":-4228276458799,"netCashRatio":-0.3269843555478199,"salesGrowthYoY":"0.033028162662172116","opGrowthYoY":"0.033028162660991726","epsGrowthYoY":"0.033025054076609925","dividendGrowthYoY":"0.03300924258792462","salesCagr3y":null,"salesCagr5y":null,"consecutiveDivIncreases":2,"currentRatio":1.0889829712804258,"deRatio":1.650987481050215,"roic":0.046365800056386505,"piotroskiFScore":7}',
  2767719068233,
  0.0464,
  0.3772,
  20980301787497,
  '2026-06-13T10:45:49.399Z'
);

INSERT OR REPLACE INTO company_metrics (
  sec_code, edinet_code, filer_name, calc_date, fiscal_month,
  metrics_json, sales, roe, equity_ratio, total_assets, updated_at
) VALUES (
  '1308',
  'E00008',
  'ラッコアセットマネジメント株式会社',
  '2025-03-31',
  '03',
  '{"edinetCode":"E00008","secCode":"1308","filerName":"ラッコアセットマネジメント株式会社","calcDate":"2025-03-31","fiscalMonth":"03","sales":"1643783724529","operatingProfit":"30651019174","recurringProfit":"28312012930","netIncome":"17147137523","comprehensiveIncome":"17575815961","netAssets":"273107639772","totalAssets":"747815803811","equityRatio":"0.3652","EPS":"47.90","dilutedEPS":"47.18","BPS":"762.87","ROE":"0.0628","roeCalculated":"0.06278527227328771","roa":"0.022929627102844297","equityRatioCalculated":"0.36520709829906745","PER":27.21,"PBR":0.77,"operatingCF":"173109919669","investingCF":"-128969061809","financingCF":"33115753607","fcf":"44140857860","cashBalance":"159856295745","payoutRatio":"0.4396","payoutRatioComputed":"0.4396932135108298","dividendPerShare":"21.06","dividendYield":0.016158249568998258,"sharesOutstanding":"358000000","currentAssets":"166595369732","currentLiabilities":"206588657646","liabilities":"474708164040","investmentSecurities":"65337884415","marketCap":466602522000,"netCash":-6291561669,"netCashRatio":-0.013483771245025547,"salesGrowthYoY":"-0.0003522985429604466","opGrowthYoY":"-0.0003522985441140538","epsGrowthYoY":"-0.0002087246921310376","dividendGrowthYoY":"0","salesCagr3y":null,"salesCagr5y":null,"consecutiveDivIncreases":0,"currentRatio":0.8064110180601952,"deRatio":1.7381724086382326,"roic":0.0627852722735176,"piotroskiFScore":7}',
  1643783724529,
  0.0628,
  0.3652,
  747815803811,
  '2026-06-13T10:45:49.399Z'
);

INSERT OR REPLACE INTO company_metrics (
  sec_code, edinet_code, filer_name, calc_date, fiscal_month,
  metrics_json, sales, roe, equity_ratio, total_assets, updated_at
) VALUES (
  '1309',
  'E00009',
  'シロクマエナジー株式会社',
  '2025-03-31',
  '03',
  '{"edinetCode":"E00009","secCode":"1309","filerName":"シロクマエナジー株式会社","calcDate":"2025-03-31","fiscalMonth":"03","sales":"1801524335274","operatingProfit":"172828189034","recurringProfit":"170946081249","netIncome":"100663560320","comprehensiveIncome":"103180149328","netAssets":"664882057274","totalAssets":"2734415464196","equityRatio":"0.2432","EPS":"154.16","dilutedEPS":"151.85","BPS":"1018.20","ROE":"0.1514","roeCalculated":"0.15140062695136955","roa":"0.03681355728054957","equityRatioCalculated":"0.24315326839679618","PER":12.56,"PBR":3.48,"operatingCF":"217221162242","investingCF":"-145267256162","financingCF":"-35854615817","fcf":"71953906080","cashBalance":"115640694299","payoutRatio":"0.0823","payoutRatioComputed":"0.08231946072300415","dividendPerShare":"12.69","dividendYield":0.006553907099580549,"sharesOutstanding":"653000000","currentAssets":"1702926296129","currentLiabilities":"888118344125","liabilities":"2069533406921","investmentSecurities":"119005109720","marketCap":1264370988800,"netCash":-608695998123,"netCashRatio":-0.4814219904718839,"salesGrowthYoY":"-0.08611830210306469","opGrowthYoY":"-0.08611830210602409","epsGrowthYoY":"-0.08608015176665881","dividendGrowthYoY":"-0.08639308855291584","salesCagr3y":null,"salesCagr5y":null,"consecutiveDivIncreases":0,"currentRatio":1.91745425302162,"deRatio":3.112632359799324,"roic":0.15140062695114184,"piotroskiFScore":8}',
  1801524335274,
  0.1514,
  0.2432,
  2734415464196,
  '2026-06-13T10:45:49.399Z'
);

INSERT OR REPLACE INTO company_metrics (
  sec_code, edinet_code, filer_name, calc_date, fiscal_month,
  metrics_json, sales, roe, equity_ratio, total_assets, updated_at
) VALUES (
  '1310',
  'E00010',
  'ウサギテクノロジーズ株式会社',
  '2025-03-31',
  '03',
  '{"edinetCode":"E00010","secCode":"1310","filerName":"ウサギテクノロジーズ株式会社","calcDate":"2025-03-31","fiscalMonth":"03","sales":"2432864376897","operatingProfit":"504293702939","recurringProfit":"474365078330","netIncome":"378736092439","comprehensiveIncome":"388204494750","netAssets":"1766400760661","totalAssets":"4251940862630","equityRatio":"0.4154","EPS":"584.47","dilutedEPS":"575.70","BPS":"2725.93","ROE":"0.2144","roeCalculated":"0.21441119188449295","roa":"0.08907369708917734","equityRatioCalculated":"0.4154339906713586","PER":29.18,"PBR":2.26,"operatingCF":"408992154726","investingCF":"-174461454647","financingCF":"-112771748507","fcf":"234530700079","cashBalance":"243470903935","payoutRatio":"0.5911","payoutRatioComputed":"0.5911516870710183","dividendPerShare":"345.51","dividendYield":0.020258771668181404,"sharesOutstanding":"648000000","currentAssets":"1291038907826","currentLiabilities":"851171158606","liabilities":"2485540101969","investmentSecurities":"167142872037","marketCap":11051532820800,"netCash":-626468131754,"netCashRatio":-0.05668608526184978,"salesGrowthYoY":"-0.04962636277055334","opGrowthYoY":"-0.04962636277047207","epsGrowthYoY":"-0.04962682320037721","dividendGrowthYoY":"-0.049621785173978875","salesCagr3y":null,"salesCagr5y":null,"consecutiveDivIncreases":0,"currentRatio":1.5167794335752525,"deRatio":1.4071212814915754,"roic":0.21441119188449295,"piotroskiFScore":9}',
  2432864376897,
  0.2144,
  0.4154,
  4251940862630,
  '2026-06-13T10:45:49.399Z'
);

INSERT OR REPLACE INTO company_metrics (
  sec_code, edinet_code, filer_name, calc_date, fiscal_month,
  metrics_json, sales, roe, equity_ratio, total_assets, updated_at
) VALUES (
  '9999',
  'E00000',
  'サンプル株式会社',
  '2025-03-31',
  '03',
  '{"edinetCode":"E00000","secCode":"9999","filerName":"サンプル株式会社","calcDate":"2025-03-31","fiscalMonth":"03","sales":"1693062911578","operatingProfit":"350133542802","recurringProfit":"337277776909","netIncome":"267773380013","comprehensiveIncome":"274467714513","netAssets":"4052182946695","totalAssets":"9600579725757","equityRatio":"0.4221","EPS":"536.62","dilutedEPS":"528.57","BPS":"8120.61","ROE":"0.0661","roeCalculated":"0.0660812662052681","roa":"0.02789137611081983","equityRatioCalculated":"0.42207690185870395","PER":24.25,"PBR":1.29,"operatingCF":"168712153757","investingCF":"-84637650849","financingCF":"143188690420","fcf":"84074502908","cashBalance":"122234614986","payoutRatio":"0.5474","payoutRatioComputed":"0.5473519436207005","dividendPerShare":"293.72","dividendYield":0.0225712141710216,"sharesOutstanding":"499000000","currentAssets":"3273483977805","currentLiabilities":"2015957068928","liabilities":"5548396779062","investmentSecurities":"92365737568","marketCap":6493504465000,"netCash":-1819704257686,"netCashRatio":-0.28023454322611296,"salesGrowthYoY":"-0.1071428571431585","opGrowthYoY":"-0.1071428571423107","epsGrowthYoY":"-0.10713632052711267","dividendGrowthYoY":"-0.10715262789920052","salesCagr3y":"0.01370033259554182","salesCagr5y":"0.025896304910184575","consecutiveDivIncreases":null,"currentRatio":1.6237865519357013,"deRatio":1.3692364959946655,"roic":0.0660812662052681,"piotroskiFScore":null}',
  1693062911578,
  0.0661,
  0.4221,
  9600579725757,
  '2026-06-13T10:45:49.399Z'
);

