-- Generated by infra/init/build-shareholder-snapshots.mjs — do not edit by hand.
PRAGMA foreign_keys = ON;

INSERT OR REPLACE INTO shareholder_snapshots (
  sec_code, period_end, doc_id, entries_json, updated_at
) VALUES (
  '9999',
  '2020-06-30',
  'SAMPLE-Q1-2021',
  '[{"name":"サンプルホールディングス株式会社","shares":128600000,"ratio":29.91},{"name":"日本サンプル年金基金","shares":43000000,"ratio":10},{"name":"サンプルキャピタルパートナーズ","shares":25800000,"ratio":6},{"name":"東京サンプル信託銀行（信託口）","shares":21500000,"ratio":5},{"name":"グローバル・インデックス・ファンド","shares":17200000,"ratio":4}]',
  '2026-06-13T10:45:50.899Z'
);

INSERT OR REPLACE INTO shareholder_snapshots (
  sec_code, period_end, doc_id, entries_json, updated_at
) VALUES (
  '9999',
  '2020-09-30',
  'SAMPLE-Q2-2021',
  '[{"name":"サンプルホールディングス株式会社","shares":128857200,"ratio":29.93},{"name":"日本サンプル年金基金","shares":43086000,"ratio":10.02},{"name":"サンプルキャピタルパートナーズ","shares":25851600,"ratio":6.02},{"name":"東京サンプル信託銀行（信託口）","shares":21543000,"ratio":5.02},{"name":"グローバル・インデックス・ファンド","shares":17234400,"ratio":4.02}]',
  '2026-06-13T10:45:50.899Z'
);

INSERT OR REPLACE INTO shareholder_snapshots (
  sec_code, period_end, doc_id, entries_json, updated_at
) VALUES (
  '9999',
  '2020-12-31',
  'SAMPLE-Q3-2021',
  '[{"name":"サンプルホールディングス株式会社","shares":129114400,"ratio":29.95},{"name":"日本サンプル年金基金","shares":43172000,"ratio":10.04},{"name":"サンプルキャピタルパートナーズ","shares":25903200,"ratio":6.04},{"name":"東京サンプル信託銀行（信託口）","shares":21586000,"ratio":5.04},{"name":"グローバル・インデックス・ファンド","shares":17268800,"ratio":4.04}]',
  '2026-06-13T10:45:50.899Z'
);

INSERT OR REPLACE INTO shareholder_snapshots (
  sec_code, period_end, doc_id, entries_json, updated_at
) VALUES (
  '9999',
  '2021-03-31',
  'SAMPLE-ANNUAL-2021',
  '[{"name":"サンプルホールディングス株式会社","shares":129371600,"ratio":29.97},{"name":"日本サンプル年金基金","shares":43258000,"ratio":10.06},{"name":"サンプルキャピタルパートナーズ","shares":25954800,"ratio":6.06},{"name":"東京サンプル信託銀行（信託口）","shares":21629000,"ratio":5.06},{"name":"グローバル・インデックス・ファンド","shares":17303200,"ratio":4.06}]',
  '2026-06-13T10:45:50.899Z'
);

INSERT OR REPLACE INTO shareholder_snapshots (
  sec_code, period_end, doc_id, entries_json, updated_at
) VALUES (
  '9999',
  '2021-06-30',
  'SAMPLE-Q1-2022',
  '[{"name":"サンプルホールディングス株式会社","shares":129628800,"ratio":29.99},{"name":"日本サンプル年金基金","shares":43344000,"ratio":10.08},{"name":"サンプルキャピタルパートナーズ","shares":26006400,"ratio":6.08},{"name":"東京サンプル信託銀行（信託口）","shares":21672000,"ratio":5.08},{"name":"グローバル・インデックス・ファンド","shares":17337600,"ratio":4.08}]',
  '2026-06-13T10:45:50.899Z'
);

INSERT OR REPLACE INTO shareholder_snapshots (
  sec_code, period_end, doc_id, entries_json, updated_at
) VALUES (
  '9999',
  '2021-09-30',
  'SAMPLE-Q2-2022',
  '[{"name":"サンプルホールディングス株式会社","shares":129886000,"ratio":30.01},{"name":"日本サンプル年金基金","shares":43430000,"ratio":10.1},{"name":"サンプルキャピタルパートナーズ","shares":26058000,"ratio":6.1},{"name":"東京サンプル信託銀行（信託口）","shares":21715000,"ratio":5.1},{"name":"グローバル・インデックス・ファンド","shares":17372000,"ratio":4.1}]',
  '2026-06-13T10:45:50.899Z'
);

INSERT OR REPLACE INTO shareholder_snapshots (
  sec_code, period_end, doc_id, entries_json, updated_at
) VALUES (
  '9999',
  '2021-12-31',
  'SAMPLE-Q3-2022',
  '[{"name":"サンプルホールディングス株式会社","shares":130143200,"ratio":30.03},{"name":"日本サンプル年金基金","shares":43516000,"ratio":10.12},{"name":"サンプルキャピタルパートナーズ","shares":26109600,"ratio":6.12},{"name":"東京サンプル信託銀行（信託口）","shares":21758000,"ratio":5.12},{"name":"グローバル・インデックス・ファンド","shares":17406400,"ratio":4.12}]',
  '2026-06-13T10:45:50.899Z'
);

INSERT OR REPLACE INTO shareholder_snapshots (
  sec_code, period_end, doc_id, entries_json, updated_at
) VALUES (
  '9999',
  '2022-03-31',
  'SAMPLE-ANNUAL-2022',
  '[{"name":"サンプルホールディングス株式会社","shares":130400400,"ratio":30.05},{"name":"日本サンプル年金基金","shares":43602000,"ratio":10.14},{"name":"サンプルキャピタルパートナーズ","shares":26161200,"ratio":6.14},{"name":"東京サンプル信託銀行（信託口）","shares":21801000,"ratio":5.14},{"name":"グローバル・インデックス・ファンド","shares":17440800,"ratio":4.14}]',
  '2026-06-13T10:45:50.899Z'
);

INSERT OR REPLACE INTO shareholder_snapshots (
  sec_code, period_end, doc_id, entries_json, updated_at
) VALUES (
  '9999',
  '2022-06-30',
  'SAMPLE-Q1-2023',
  '[{"name":"サンプルホールディングス株式会社","shares":130657600,"ratio":30.07},{"name":"日本サンプル年金基金","shares":43688000,"ratio":10.16},{"name":"サンプルキャピタルパートナーズ","shares":26212800,"ratio":6.16},{"name":"東京サンプル信託銀行（信託口）","shares":21844000,"ratio":5.16},{"name":"グローバル・インデックス・ファンド","shares":17475200,"ratio":4.16}]',
  '2026-06-13T10:45:50.899Z'
);

INSERT OR REPLACE INTO shareholder_snapshots (
  sec_code, period_end, doc_id, entries_json, updated_at
) VALUES (
  '9999',
  '2022-09-30',
  'SAMPLE-Q2-2023',
  '[{"name":"サンプルホールディングス株式会社","shares":130914800,"ratio":30.09},{"name":"日本サンプル年金基金","shares":43774000,"ratio":10.18},{"name":"サンプルキャピタルパートナーズ","shares":26264400,"ratio":6.18},{"name":"東京サンプル信託銀行（信託口）","shares":21887000,"ratio":5.18},{"name":"グローバル・インデックス・ファンド","shares":17509600,"ratio":4.18}]',
  '2026-06-13T10:45:50.899Z'
);

INSERT OR REPLACE INTO shareholder_snapshots (
  sec_code, period_end, doc_id, entries_json, updated_at
) VALUES (
  '9999',
  '2022-12-31',
  'SAMPLE-Q3-2023',
  '[{"name":"サンプルホールディングス株式会社","shares":131172000,"ratio":30.11},{"name":"日本サンプル年金基金","shares":43860000,"ratio":10.2},{"name":"サンプルキャピタルパートナーズ","shares":26316000,"ratio":6.2},{"name":"東京サンプル信託銀行（信託口）","shares":21930000,"ratio":5.2},{"name":"グローバル・インデックス・ファンド","shares":17544000,"ratio":4.2}]',
  '2026-06-13T10:45:50.899Z'
);

INSERT OR REPLACE INTO shareholder_snapshots (
  sec_code, period_end, doc_id, entries_json, updated_at
) VALUES (
  '9999',
  '2023-03-31',
  'SAMPLE-ANNUAL-2023',
  '[{"name":"サンプルホールディングス株式会社","shares":131429200,"ratio":30.13},{"name":"日本サンプル年金基金","shares":43946000,"ratio":10.22},{"name":"サンプルキャピタルパートナーズ","shares":26367600,"ratio":6.22},{"name":"東京サンプル信託銀行（信託口）","shares":21973000,"ratio":5.22},{"name":"グローバル・インデックス・ファンド","shares":17578400,"ratio":4.22}]',
  '2026-06-13T10:45:50.899Z'
);

INSERT OR REPLACE INTO shareholder_snapshots (
  sec_code, period_end, doc_id, entries_json, updated_at
) VALUES (
  '9999',
  '2023-06-30',
  'SAMPLE-Q1-2024',
  '[{"name":"サンプルホールディングス株式会社","shares":131686400,"ratio":30.15},{"name":"日本サンプル年金基金","shares":44032000,"ratio":10.24},{"name":"サンプルキャピタルパートナーズ","shares":26419200,"ratio":6.24},{"name":"東京サンプル信託銀行（信託口）","shares":22016000,"ratio":5.24},{"name":"グローバル・インデックス・ファンド","shares":17612800,"ratio":4.24}]',
  '2026-06-13T10:45:50.899Z'
);

INSERT OR REPLACE INTO shareholder_snapshots (
  sec_code, period_end, doc_id, entries_json, updated_at
) VALUES (
  '9999',
  '2023-09-30',
  'SAMPLE-Q2-2024',
  '[{"name":"サンプルホールディングス株式会社","shares":131943600,"ratio":30.17},{"name":"日本サンプル年金基金","shares":44118000,"ratio":10.26},{"name":"サンプルキャピタルパートナーズ","shares":26470800,"ratio":6.26},{"name":"東京サンプル信託銀行（信託口）","shares":22059000,"ratio":5.26},{"name":"グローバル・インデックス・ファンド","shares":17647200,"ratio":4.26}]',
  '2026-06-13T10:45:50.899Z'
);

INSERT OR REPLACE INTO shareholder_snapshots (
  sec_code, period_end, doc_id, entries_json, updated_at
) VALUES (
  '9999',
  '2023-12-31',
  'SAMPLE-Q3-2024',
  '[{"name":"サンプルホールディングス株式会社","shares":132200800,"ratio":30.19},{"name":"日本サンプル年金基金","shares":44204000,"ratio":10.28},{"name":"サンプルキャピタルパートナーズ","shares":26522400,"ratio":6.28},{"name":"東京サンプル信託銀行（信託口）","shares":22102000,"ratio":5.28},{"name":"グローバル・インデックス・ファンド","shares":17681600,"ratio":4.28}]',
  '2026-06-13T10:45:50.899Z'
);

INSERT OR REPLACE INTO shareholder_snapshots (
  sec_code, period_end, doc_id, entries_json, updated_at
) VALUES (
  '9999',
  '2024-03-31',
  'SAMPLE-ANNUAL-2024',
  '[{"name":"サンプルホールディングス株式会社","shares":132458000,"ratio":30.21},{"name":"日本サンプル年金基金","shares":44290000,"ratio":10.3},{"name":"サンプルキャピタルパートナーズ","shares":26574000,"ratio":6.3},{"name":"東京サンプル信託銀行（信託口）","shares":22145000,"ratio":5.3},{"name":"グローバル・インデックス・ファンド","shares":17716000,"ratio":4.3}]',
  '2026-06-13T10:45:50.899Z'
);

INSERT OR REPLACE INTO shareholder_snapshots (
  sec_code, period_end, doc_id, entries_json, updated_at
) VALUES (
  '9999',
  '2024-06-30',
  'SAMPLE-Q1-2025',
  '[{"name":"サンプルホールディングス株式会社","shares":132715200,"ratio":30.23},{"name":"日本サンプル年金基金","shares":44376000,"ratio":10.32},{"name":"サンプルキャピタルパートナーズ","shares":26625600,"ratio":6.32},{"name":"東京サンプル信託銀行（信託口）","shares":22188000,"ratio":5.32},{"name":"グローバル・インデックス・ファンド","shares":17750400,"ratio":4.32}]',
  '2026-06-13T10:45:50.899Z'
);

INSERT OR REPLACE INTO shareholder_snapshots (
  sec_code, period_end, doc_id, entries_json, updated_at
) VALUES (
  '9999',
  '2024-09-30',
  'SAMPLE-Q2-2025',
  '[{"name":"サンプルホールディングス株式会社","shares":132972400,"ratio":30.25},{"name":"日本サンプル年金基金","shares":44462000,"ratio":10.34},{"name":"サンプルキャピタルパートナーズ","shares":26677200,"ratio":6.34},{"name":"東京サンプル信託銀行（信託口）","shares":22231000,"ratio":5.34},{"name":"グローバル・インデックス・ファンド","shares":17784800,"ratio":4.34}]',
  '2026-06-13T10:45:50.899Z'
);

INSERT OR REPLACE INTO shareholder_snapshots (
  sec_code, period_end, doc_id, entries_json, updated_at
) VALUES (
  '9999',
  '2024-12-31',
  'SAMPLE-Q3-2025',
  '[{"name":"サンプルホールディングス株式会社","shares":133229600,"ratio":30.27},{"name":"日本サンプル年金基金","shares":44548000,"ratio":10.36},{"name":"サンプルキャピタルパートナーズ","shares":26728800,"ratio":6.36},{"name":"東京サンプル信託銀行（信託口）","shares":22274000,"ratio":5.36},{"name":"グローバル・インデックス・ファンド","shares":17819200,"ratio":4.36}]',
  '2026-06-13T10:45:50.899Z'
);

INSERT OR REPLACE INTO shareholder_snapshots (
  sec_code, period_end, doc_id, entries_json, updated_at
) VALUES (
  '9999',
  '2025-03-31',
  'SAMPLE-ANNUAL-2025',
  '[{"name":"サンプルホールディングス株式会社","shares":133486800,"ratio":30.29},{"name":"日本サンプル年金基金","shares":44634000,"ratio":10.38},{"name":"サンプルキャピタルパートナーズ","shares":26780400,"ratio":6.38},{"name":"東京サンプル信託銀行（信託口）","shares":22317000,"ratio":5.38},{"name":"グローバル・インデックス・ファンド","shares":17853600,"ratio":4.38}]',
  '2026-06-13T10:45:50.899Z'
);

